"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import styles from "./banco-perguntas-admin.module.css";

type Row={id:number;question:string;status:string;origin:string;shortAnswer:string;fullAnswer:string;version:number;sourceCount:number};
type Sub={id:number;question:string;shortAnswer:string;fullAnswer:string;evidence:any[];createdAt:string};
type Imp={id:number;question:string;shortAnswer:string;fullAnswer:string;status:string;duplicateQuestion?:string|null;duplicateScore?:number;selected:boolean;force?:boolean};

export default function AdminBancoPerguntas(){
 const [ready,setReady]=useState(false),[auth,setAuth]=useState(false),[tab,setTab]=useState<"bank"|"new"|"import"|"review">("bank"),[items,setItems]=useState<Row[]>([]),[subs,setSubs]=useState<Sub[]>([]),[counts,setCounts]=useState<any>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const [question,setQuestion]=useState(""),[shortAnswer,setShortAnswer]=useState(""),[fullAnswer,setFullAnswer]=useState(""),[aliases,setAliases]=useState(""),[status,setStatus]=useState("approved");
 const [file,setFile]=useState<File|null>(null),[importId,setImportId]=useState<number|null>(null),[preview,setPreview]=useState<Imp[]>([]),[summary,setSummary]=useState(""),[publish,setPublish]=useState(true);
 async function api(body:any){const r=await fetch("/api/question-bank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.status===401){setAuth(false);throw Error("Sessão administrativa expirada.")}if(!r.ok)throw Error(d.error||"Falha na operação.");return d}
 async function load(){const [b,s]=await Promise.all([api({action:"admin-list"}),api({action:"review-list"})]);setItems(b.items||[]);setCounts(b.counts||{});setSubs(s.items||[])}
 useEffect(()=>{fetch("/api/admin/session",{cache:"no-store"}).then(r=>r.json()).then(async d=>{setAuth(!!d.authenticated);if(d.authenticated)await load()}).catch(()=>setAuth(false)).finally(()=>setReady(true))},[])
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setErr("");setMsg("");try{const d=await api({action:"create",question,shortAnswer,fullAnswer,aliases:aliases.split(/\n|;/).map(x=>x.trim()).filter(Boolean),status});setMsg(`Pergunta cadastrada. ID ${d.id}.`);setQuestion("");setShortAnswer("");setFullAnswer("");setAliases("");await load();setTab("bank")}catch(e){setErr(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function changeStatus(id:number,next:string){setBusy(true);setErr("");try{await api({action:"status",id,status:next});await load()}catch(e){setErr(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function review(sub:Sub,decision:"approve"|"reject"){setBusy(true);setErr("");try{await api({action:"review",id:sub.id,decision,shortAnswer:sub.shortAnswer,fullAnswer:sub.fullAnswer});setMsg(decision==="approve"?"Sugestão aprovada e publicada.":"Sugestão rejeitada.");await load()}catch(e){setErr(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 function pdfjs(){const w=window as any;if(w.pdfjsLib)return Promise.resolve(w.pdfjsLib);if(w.__qbPdf)return w.__qbPdf;w.__qbPdf=new Promise((resolve,reject)=>{const done=()=>{window.removeEventListener("qb-pdf",done);if(!w.pdfjsLib)return reject(Error("PDF.js não carregou."));w.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";resolve(w.pdfjsLib)};window.addEventListener("qb-pdf",done,{once:true});const s=document.createElement("script");s.type="module";s.textContent=`import * as pdfjsLib from "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs"; window.pdfjsLib=pdfjsLib; window.dispatchEvent(new Event("qb-pdf"));`;s.onerror=()=>reject(Error("Falha ao carregar PDF.js."));document.head.appendChild(s)}).finally(()=>w.__qbPdf=null);return w.__qbPdf}
 function mammoth(){const w=window as any;if(w.mammoth)return Promise.resolve(w.mammoth);if(w.__qbM)return w.__qbM;w.__qbM=new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js";s.onload=()=>w.mammoth?resolve(w.mammoth):reject(Error("Mammoth não carregou."));s.onerror=()=>reject(Error("Falha ao carregar leitor DOCX."));document.head.appendChild(s)}).finally(()=>w.__qbM=null);return w.__qbM}
 async function textFrom(f:File){const n=f.name.toLowerCase();if(n.endsWith(".pdf")){const p:any=await pdfjs();const doc=await p.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;const pages=[] as string[];for(let i=1;i<=doc.numPages;i++){const pg=await doc.getPage(i),c=await pg.getTextContent();pages.push((c.items||[]).map((x:any)=>x?.str||"").join(" ").replace(/\s+/g," ").trim())}return pages.join("\n\n")}if(n.endsWith(".docx")){const m:any=await mammoth();const r=await m.extractRawText({arrayBuffer:await f.arrayBuffer()});return String(r.value||"").trim()}return await f.text()}
 async function analyze(){if(!file)return;setBusy(true);setErr("");setPreview([]);setSummary("");try{const text=await textFrom(file);const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer()))).map(x=>x.toString(16).padStart(2,"0")).join("");const type=file.name.toLowerCase().endsWith(".pdf")?"pdf":file.name.toLowerCase().endsWith(".docx")?"docx":"txt";const d=await api({action:"import-preview",filename:file.name,fileType:type,sha256:hash,text});setImportId(d.importId);setPreview(d.items||[]);setSummary(`${d.total} detectada(s) · ${d.ready} pronta(s) · ${d.review} para revisão · ${d.duplicates} duplicada(s).`)}catch(e){setErr(e instanceof Error?e.message:"Falha na análise.")}finally{setBusy(false)}}
 function patch(id:number,p:Partial<Imp>){setPreview(v=>v.map(x=>x.id===id?{...x,...p}:x))}
 async function commit(){if(!importId)return;setBusy(true);setErr("");try{const d=await api({action:"import-commit",importId,items:preview.filter(x=>x.selected),publishImmediately:publish});setMsg(`${d.created} pergunta(s) importada(s). ${d.skipped} duplicada(s) ignorada(s).`);setPreview([]);setImportId(null);setFile(null);setSummary("");await load();setTab("bank")}catch(e){setErr(e instanceof Error?e.message:"Falha na importação.")}finally{setBusy(false)}}
 if(!ready)return <main className={styles.shell}><div className={styles.login}>Verificando acesso…</div></main>;
 if(!auth)return <main className={styles.shell}><div className={styles.login}><h1>Banco de Perguntas</h1><p>Entre primeiro na administração principal.</p><a href="/admin">Ir para Administração →</a></div></main>;
 return <main className={styles.shell}><header className={styles.header}><div><span>Administração</span><h1>Banco de Perguntas</h1><p>Cadastre, importe, revise e publique perguntas e respostas.</p></div><div><a href="/banco-perguntas">Ver banco público</a><a href="/admin">← Administração</a></div></header><section className={styles.stats}><div><b>{counts.total||0}</b><span>Total</span></div><div><b>{counts.approved||0}</b><span>Aprovadas</span></div><div><b>{counts.review||0}</b><span>Em revisão</span></div><div><b>{subs.length}</b><span>Sugestões</span></div></section><nav className={styles.tabs}>{[["bank","Banco"],["new","Nova pergunta"],["import","Importar PDF/DOCX"],["review",`Em revisão (${subs.length})`]].map(([k,l])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k as any)}>{l}</button>)}</nav>{msg&&<div className={styles.success}>{msg}</div>}{err&&<div className={styles.error}>{err}</div>}
 {tab==="bank"&&<section className={styles.panel}><h2>Perguntas cadastradas</h2><div className={styles.list}>{items.map(x=><article key={x.id}><div className={styles.meta}><span className={styles[x.status]||""}>{x.status}</span><span>{x.origin}</span><span>v{x.version}</span><span>{x.sourceCount} fonte(s)</span></div><h3>{x.question}</h3><p>{x.shortAnswer||x.fullAnswer}</p><div className={styles.actions}>{x.status!=="approved"&&<button disabled={busy} onClick={()=>changeStatus(x.id,"approved")}>Aprovar</button>}{x.status!=="review"&&<button disabled={busy} onClick={()=>changeStatus(x.id,"review")}>Revisar</button>}{x.status!=="archived"&&<button disabled={busy} onClick={()=>changeStatus(x.id,"archived")}>Arquivar</button>}</div></article>)}</div></section>}
 {tab==="new"&&<form className={styles.panel} onSubmit={create}><h2>Nova pergunta e resposta</h2><label>Pergunta<textarea rows={3} value={question} onChange={e=>setQuestion(e.target.value)} required/></label><div className={styles.grid}><label>Resposta simplificada<textarea rows={8} value={shortAnswer} onChange={e=>setShortAnswer(e.target.value)}/></label><label>Resposta ampla<textarea rows={12} value={fullAnswer} onChange={e=>setFullAnswer(e.target.value)}/></label></div><label>Variações da pergunta<textarea rows={5} value={aliases} onChange={e=>setAliases(e.target.value)} placeholder="Uma por linha"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="approved">Aprovada</option><option value="review">Em revisão</option><option value="draft">Rascunho</option></select></label><button className={styles.primary} disabled={busy}>{busy?"Salvando…":"Cadastrar no Banco"}</button></form>}
 {tab==="import"&&<section className={styles.panel}><h2>Importar perguntas de PDF ou DOCX</h2><p>O arquivo é lido no navegador e nada é gravado antes da sua confirmação.</p><div className={styles.import}><input type="file" accept=".pdf,.docx,.txt" onChange={(e:ChangeEvent<HTMLInputElement>)=>{setFile(e.target.files?.[0]||null);setPreview([]);setImportId(null);setSummary("")}}/><button disabled={!file||busy} onClick={analyze}>{busy?"Analisando…":"Analisar arquivo"}</button></div>{file&&<small>{file.name} · {(file.size/1024/1024).toFixed(2)} MB</small>}{summary&&<div className={styles.success}>{summary}</div>}{!!preview.length&&<><label className={styles.check}><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/> Publicar imediatamente como aprovado</label><div className={styles.list}>{preview.map((x,i)=><article key={x.id}><div className={styles.meta}><label className={styles.check}><input type="checkbox" checked={x.selected} onChange={e=>patch(x.id,{selected:e.target.checked})}/>{String(i+1).padStart(2,"0")}</label><span className={styles[x.status]||""}>{x.status}</span></div>{x.duplicateQuestion&&<div className={styles.dup}>Possível semelhante: “{x.duplicateQuestion}” {x.duplicateScore?`· ${Math.round(x.duplicateScore*100)}%`:""}</div>}<label>Pergunta<textarea rows={3} value={x.question} onChange={e=>patch(x.id,{question:e.target.value})}/></label><div className={styles.grid}><label>Resposta simplificada<textarea rows={6} value={x.shortAnswer} onChange={e=>patch(x.id,{shortAnswer:e.target.value})}/></label><label>Resposta ampla<textarea rows={9} value={x.fullAnswer} onChange={e=>patch(x.id,{fullAnswer:e.target.value})}/></label></div>{(x.status==="duplicate"||x.status==="review")&&<label className={styles.check}><input type="checkbox" checked={!!x.force} onChange={e=>patch(x.id,{force:e.target.checked})}/> Importar mesmo assim após minha revisão</label>}</article>)}</div><button className={styles.primary} disabled={busy} onClick={commit}>{busy?"Importando…":"Confirmar importação selecionada"}</button></>}</section>}
 {tab==="review"&&<section className={styles.panel}><h2>Sugestões dos usuários</h2>{!subs.length?<p>Nenhuma sugestão aguardando revisão.</p>:<div className={styles.list}>{subs.map(s=><article key={s.id}><div className={styles.meta}><span className={styles.review}>review</span><span>{new Date(s.createdAt).toLocaleString("pt-BR")}</span></div><h3>{s.question}</h3><details open><summary>Resposta simplificada</summary><p>{s.shortAnswer}</p></details><details><summary>Resposta ampla</summary><p>{s.fullAnswer}</p></details><div className={styles.actions}><button disabled={busy} onClick={()=>review(s,"approve")}>Aprovar e publicar</button><button disabled={busy} onClick={()=>review(s,"reject")}>Rejeitar</button></div></article>)}</div>}</section>}
 </main>
}
